Public Enum TypeError
    login = 1
    logout = 2
    open_form = 3
    backup = 4
    retore = 5
    lng_change = 6
    create_user = 7
    modify_user = 8
    disable_user = 9
    pass_change = 10
    client_registry = 11
    client_inscription = 12
    access_registry = 13
    desc_registry = 14
    desc_aprobe = 15
    routine_reg = 16
    reporting = 17
End Enum
