//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DAL
{
	using BLL;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MP_Usuario
	{
		public virtual usuario Seleccionar(object usuario)
		{
			throw new System.NotImplementedException();
		}

		public virtual boolean Insertar(object usuario)
		{
			throw new System.NotImplementedException();
		}

		public virtual boolean Actualizar(object usuari)
		{
			throw new System.NotImplementedException();
		}

	}
}

